services:
  pac-server:
    image: nginx:alpine
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "1024k"
    volumes:
      - type: bind
        source: ./pac
        target: /usr/share/nginx/html
      - type: bind
        source: ./nginx-config
        target: /etc/nginx/conf.d.test.d
    ports:
      - "8081:80"
  proxy-core:
    build: 
      context: .
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "1024k"
    volumes:
      - type: bind
        source: ./squid-config
        target: /etc/squid
    ports:
      - 3128:3128
      - 3128:3128/UDP
      - 8080:3128
      - 8080:3128/UDP
