services:
  pac-server:
    image: nginx:alpine
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "1024k"
    volumes:
      - ./pac:/usr/share/nginx/html
    ports:
      - "8081:80"
  proxy-core:
    build: 
      context: .
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "1024k"
    ports:
      - 3128:3128
      - 3128:3128/UDP
      - 8080:3128
      - 8080:3128/UDP
    volumes:
      - type: bind
        source: ./config-squid
        target: /etc/squid
