name: Docker compose Build
on:
  workflow_dispatch:
  delete: 
  create: 
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Image
        run: docker compose build --no-cache

      - name: Print the config
        run: docker compose config

      - name: Start process
        run: docker compose up -d

      - name: Squid version
        run: docker compose exec proxy-server squid --version
